### ISSUE TITLE
Expand item

### ISSUE THREAD

**Issue by Feboli** [SilenceDut/ExpandableLayout#13]
hi,
How can I expand an item permanently?
Thank you.

**Comment by SilenceDut** [comment]
Hi,you can extend ExpandableLayout and overwrite the method toggle,just like this 
   ```
@Override
public void toggle() {
        if(!isExpanded()) {
            expand();
        }
    }

```

**Comment by Feboli** [comment]
Thanks for answer but the problem is where extend ExpandableLayout, i can't do it in activity or fragment

**Comment by SilenceDut** [comment]
you can create a layout which extends the ExpandableLayout,and than use your layout
