### ISSUE TITLE
Failed to compile lib on graddle dependencies

### ISSUE THREAD

**Issue by caroltr** [SilenceDut/ExpandableLayout#3]
I'm trying to add this library in my project, doing exactly what was specified for graddle:

allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}

and 

compile 'com.github.SilenceDut:ExpandableLayout:1.0.0'

but always says:
Failed to resolve: com.github.SilenceDut:ExpandableLayout:1.0.1

Am I doing something wrong?

**Comment by SilenceDut** [comment]
hi carolt, use com.github.SilenceDut:ExpandableLayout:v1.0.1 .
you missed the "v" character
