### ISSUE TITLE
expWithParentScroll, CardView, and RecyclerView: Incorrect Collapse Behavior

### ISSUE THREAD

**Issue by commonsguy** [SilenceDut/ExpandableLayout#4]
If you look in `app/src/main/res/layout/row.xml` of the attached project, you will see that I use `ExpandableLayout` in a row for a `RecyclerView`, and I have `app:expWithParentScroll="true"` set. However, the `ExpandableLayout` is wrapped in a `CardView`.

When you run the app, expanding and collapsing a row does not return the row to its original state:

![expandablelayout-bug](https://cloud.githubusercontent.com/assets/103772/17813108/fa885b9a-65f7-11e6-93d8-fb2bf426f921.gif)

If you comment out the `CardView`, `ExpandableLayout` works correctly:

![expandablelayout-bug2](https://cloud.githubusercontent.com/assets/103772/17813170/3afd595a-65f8-11e6-9765-62e37fb6b69f.gif)

It feels like `ExpandableLayout` does not like being wrapped in something else for the row, like the `CardView`. I do not know if it is a bug, a known limitation, or if I am doing something wrong with the `CardView` somehow.

[ExpandableRow.zip](https://github.com/SilenceDut/ExpandableLayout/files/427213/ExpandableRow.zip)

Thanks!

**Comment by SilenceDut** [comment]
Hi commonsguy,
      so far，it's a limitation or you can say it's a bug ,I didn't found the limitation before,
and I willing to work at it.
     Thanks for your proposal !
     Have a nice day!

**Comment by SilenceDut** [comment]
Hi commonsguy,

```
The bug had been fixed.
Use compile 'com.github.SilenceDut:ExpandableLayout:1.2.0' in you project.
```

Have a nice day!

**Comment by commonsguy** [comment]
I can confirm that this is fixed. Many thanks!
